### ISSUE TITLE
Use static analyser tools to catch bugs

### ISSUE THREAD

**Issue by pushrbx** [jikan-me/jikan-rest#319]
Static analysers would help us spot syntax errors across php versions, and those little nuances  where array functions behave differently across php versions.

https://github.com/phpstan/phpstan
https://github.com/nunomaduro/larastan  -- I wonder if there is a lumen alternative to this

Rough github action sketch:
```yml
    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - '8.1'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl,mbstring
                    tools: composer
                    coverage: none
                    ini-values: memory_limit=-1
            -   name: Install dependencies
                run: composer install --no-interaction
            -   name: Run PHPStan Analysis
                run: ./vendor/bin/phpstan analyse --no-interaction --no-progress --ansi
```
